spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/cipheraudit
    username: cipher
    password: SuperSecret123!
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
